### ISSUE TITLE
Where can I download a client?

### ISSUE THREAD

**Issue by lugiah** [Bratah123/ElectronMS#2]
Hi. Thanks for sharing and guiding for building.
I already checked the Set-up Guide of this project, but the client link is dead now.
Is there any chance to get this?
Thank you.

**Comment by KOOKIIEStudios** [comment]
Unfortunately, the client was hosted on SoulGirlJP's Google Drive account when they were setting up the original Azure v316 repository.
You'll have to find a v316 client yourself instead.
